
package Enums;

public enum Optionals {
    NONE,
    PASTIGLIE_ROSSE,
    CERCHI_MAGGIORATI,
    VETRI_OSCURATI,
    COLORE_CARROZZERIA_PERSONALIZZATO,
    ABBONAMENTO_ANNUALE_PER_COLONNINE_PUBBLICHE,
    TETTO_APRIBILE,
    INTERNO_IN_PELLE,
    IMPIANTO_AUDIO_HARMAN_KARDON,
    CAMBIO_AUTOMATICO
}